### ISSUE TITLE
could we publish a release to npm?

### ISSUE THREAD

**Issue by eccegordo** [bantic/three-way-merger#5]
Would it be possible to publish a 0.0.1 release to npm?

@seawatts has an implementation of our updater in his addon and we are using this package-merger repo and it would be handy to be able to reference a version.

https://github.com/seawatts/ember-cli-commands

https://github.com/seawatts/ember-cli-commands/pull/46

**Comment by bantic** [comment]
@eccegordo Absolutely. Unfortunately, package-merger is taken as a name so this repo needs to be renamed. Any suggestions? I'm thinking `three-way-json-merge`, `package-merger-three-way`, or just `three-way-merge`.

**Comment by eccegordo** [comment]
ping @seawatts? Preferences?

I like `three-way-merge`

**Comment by seawatts** [comment]
Hmm, if it didn't have the name `package` in it we would have to make it a little more generic to not just look at `dependencies` and devDependencies` Which might be a good thing because then we could apply it generically to any json blob. e.x `bower.json`

**Comment by eccegordo** [comment]
Yeah that is my thinking as well. There maybe other use cases for this such as managing other configuration files.

Do we imagine this project to only work with JSON or could it ever do anything else. Might be more explicit to have json in the name but I like generic.

**Comment by bantic** [comment]
@seawatts and @eccegordo Awesome, I agree. I have a PR here: #6

I think the API should change to take 3 json blobs and it will 3-way merge them (rather than expecting an object with `dependencies` and `devDependencies`). But that can happen later.

**Comment by bantic** [comment]
released as `three-way-merger@0.2.0`
