### ISSUE TITLE
Add support for additional dependency types to `Merger.merge`.

### ISSUE THREAD

**Issue by rwjblue** [bantic/three-way-merger#7]
I would like to add support for `optionalDependencies`, `peerDependencies`, and `bundledDependencies` to `require('three-way-merge').merge`. I _believe_ that this is as simple as adding a few more instances of [this kind of block](https://github.com/bantic/three-way-merger/blob/007e64b95bd650118161caa0715ac273f1dfa334/lib/three-way-merger.js#L17-L21) for each of the keys listed.

@bantic Does that seem correct to you?

**Comment by bantic** [comment]
@rwjblue Yep, that's exactly right. I have some OSS time at the end of this week and will clean this up. A PR would be accepted, of course, if you need it earlier. :)

**Comment by rwjblue** [comment]
@bantic Sounds awesome. I don't think I'm blocked or anything at the moment.

**Comment by kellyselden** [comment]
I've got a branch started for this for use in https://github.com/kellyselden/ember-cli-update

**Comment by bantic** [comment]
@kellyselden Awesome — apologies that I haven't been able to add it yet. If you make a PR I'll merge it in asap.
